---
title: Initial sand tiger shark GAM exploration
date: last-modified
execute:
  message: false
  warning: false
---
```{r}
#| echo: false
if (grepl("notebooks", getwd())) {
  Sys.setenv(DATA_DIR = "../..")
} else {
  Sys.setenv(DATA_DIR = "")
}
```

```{r}
#| label: libs
library(arrow) # Data import
library(dplyr) # Data manipulation
library(sf) # Spatial
library(ggplot2) # Data visualization
library(mgcv) # GAM fitting
library(gratia) # GAM visualization

theme_set(theme_minimal())
```

## Sand tiger shark _Carcharias taurus_

```{r}
#| label: st-import
st_filepath <- file.path(Sys.getenv("DATA_DIR"), "data/RAW/sandtigers.csv")

sandtiger <- open_dataset(st_filepath, format = "csv") |>
  mutate(
    datetime = strptime(DateandTime, format = "%m/%d/%Y %H:%M", tz = "UTC"),
    wk = week(datetime),
    yr = year(datetime)
  ) |>
  group_by(Transmitter, wk, yr) |>
  summarize(
    med_lon = median(Longitude, na.rm = TRUE),
    med_lat = median(Latitude, na.rm = TRUE)
  ) |>
  collect()
```


```{r}
#| label: st-plot
#| fig-cap: "Weekly median latitude of sand tiger sharks."
ggplot(sandtiger) +
  geom_point(aes(x = wk, y = med_lat), alpha = 0.4, color = "orange") +
  facet_wrap(~yr) +
  labs(x = "Week of year", y = "Weekly median latitude") +
  theme(axis.title = element_text(size = 12))
```

```{r}
#| label: st-proj-center
#| echo: false
projection_center <- open_dataset(st_filepath, format = "csv") |>
  distinct(Latitude, Longitude) |>
  summarize(
    lon0 = median(Longitude, na.rm = TRUE),
    lat0 = median(Latitude, na.rm = TRUE)
  ) |>
  collect()

projection_center
```

```{r}
#| label: st-proj-string
proj_string <- paste0(
  "+proj=aeqd +lon_0=",
  round(projection_center$lon0, 3),
  " +lat_0=",
  round(projection_center$lat0, 3)
)

proj_string
```

```{r}
#| label: st-aeqd-plot
#| fig-cap: "Distribution of sand tiger detections in an AEQD projection centered on the median receiver location."
sandtiger_sf <- sandtiger |>
  st_as_sf(coords = c("med_lon", "med_lat"), crs = 4326) |>
  st_transform(proj_string)

sandtiger_sf |>
  distinct(geometry) |>
  ggplot() +
  geom_sf() +
  coord_sf(datum = proj_string)
```

```{r}
#| label: st-azimuth
migration_azimuth <- sandtiger_sf |>
  # Extract AEQD coordinates
  st_coordinates() |>
  # Run PCA
  prcomp() |>
  # Extract PCA loadings
  _$rotation |>
  # Transpose matrix
  t() |>
  # Find coordinates of a second location on the X axis.
  # Here we use 1 km but it could be any value
  (\(.) c(1e3, 0) %*% .)() |>
  # Find the angle between true north and migration north
  (\(.) atan2(.[1], .[2]) * 180 / pi)()

# Measure clockwise from north
migration_azimuth <- ifelse(
  migration_azimuth < 0,
  180 + migration_azimuth,
  migration_azimuth
)

migration_azimuth
```

```{r}
#| label: st-rotate
st_crs(sandtiger_sf) <- "+proj=aeqd +lat_0=90 +lon_0=0"
proj_rotated <- paste0("+proj=aeqd +lat_0=90 +lon_0=", migration_azimuth)

sandtiger_migration_north <- sandtiger_sf |>
  st_transform(proj_rotated) |>
  # extract coordinates for modeling purposes
  mutate(x = st_coordinates(geometry)[, 1], y = st_coordinates(geometry)[, 2])


ggplot(sandtiger_migration_north) +
  geom_sf() +
  coord_sf(datum = proj_rotated)
```

```{r}
#| label: st-synchrony
ggplot(sandtiger_migration_north) +
  geom_point(aes(x = wk, y = x), alpha = 0.4, color = "orange") +
  facet_wrap(~yr) +
  labs(
    title = "Migration synchrony",
    x = "Week of year",
    y = "Distance along the migration vector"
  ) +
  theme(axis.title = element_text(size = 12))
```

```{r}
#| label: st-front
ggplot(sandtiger_migration_north) +
  geom_point(aes(x = wk, y = y, color = group), alpha = 0.4, color = "orange") +
  facet_wrap(~yr) +
  labs(
    title = "Migration front",
    x = "Week of year",
    y = "Distance across the migration vector"
  ) +
  theme(axis.title = element_text(size = 12))
```

### Initial GAM
#### Migration vector


```{r}
#| label: st-gam-yr-re
model_data <- sandtiger_migration_north |>
  mutate(yr_f = factor(yr))

m1_st <- model_data |>
  gam(
    x ~ s(wk, k = 27, bs = "cc") + s(yr_f, bs = "re"),
    knots = list(wk = c(1, 53)),
    data = _,
    method = "REML"
  )

summary(m1_st)
draw(m1_st, select = "s(wk)", residuals = TRUE)
```

```{r}
#| label: st-gam-by-yr
m2_st <- model_data |>
  gam(
    x ~ yr_f + s(wk, by = yr_f, k = 27, bs = "cc"),
    knots = list(wk = c(1, 53)),
    data = _,
    method = "REML"
  )


summary(m2_st)
draw(m2_st, select = c("s(wk)"), partial_match = TRUE, residuals = TRUE)
```

#### Migration front

We'll do the same with the migration front (the deviation from the migration vector).
```{r}
#| label: st-gam-front-yr-re
m1_mf <- model_data |>
  gam(
    y ~ s(wk, k = 27, bs = "cc") + s(yr_f, bs = "re"),
    knots = list(wk = c(1, 53)),
    data = _,
    method = "REML"
  )

summary(m1_mf)
draw(m1_mf, select = "s(wk)", residuals = TRUE)
```

```{r}
#| label: st-gam-front-by-yr
m2_mf <- model_data |>
  gam(
    y ~ yr_f + yr_f + s(wk, by = yr_f, k = 27, bs = "cc"),
    knots = list(wk = c(1, 53)),
    data = _,
    method = "REML"
  )

summary(m2_mf)
draw(m2_mf, select = "s(wk)", residuals = TRUE, partial_match = TRUE)
```


### Model evaluation

```{r}
#| label: appraise
appraise(m1_st)
appraise(m2_st)
appraise(m1_mf)
appraise(m2_mf)
```