project:
  type: book

book:
  title: "Flyway Assessment of Offshore Wind Farm Impacts on Migratory Fishes"
  author: "Michael O'Brien, Matthew Breece, Aaron Carlise, Dewayne Fox, Bradley Wetherbee, and David Secor"
  date: Sys.Date()
  chapters:
    - index.qmd
    - geodesic.qmd
    - migration_north.qmd
    - projection_error.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

execute:
  freeze: auto