---
title: Projection Error
date: 2026-03-23
format: html
---

```{r}
# remotes::install_github("hypertidy/geographiclib")
library(geographiclib)
library(data.table)
library(sf)
library(ggplot2)
library(patchwork)
sb <- qs2::qs_read("../data/RAW/hud_detects.qs2") |>
  as.data.table() |>
  unique(by = c("long", "lat")) |>
  _[, .(lon = long, lat = lat)]
atl <- fread("../data/RAW/fixed_rounded_station_locations.csv") |>
  unique(by = c("r.lon", "r.lat")) |>
  _[, .(lon = r.lon, lat = r.lat)]
st <- fread("../data/RAW/sandtigers.csv") |>
  unique(by = c("Longitude", "Latitude")) |>
  _[, .(lon = Longitude, lat = Latitude)]

locations <- list(sb = sb, atl = atl, st = st)
```

```{r}
truth <- lapply(locations, geodesic_distance_matrix)
centers <- lapply(
  locations,
  \(.) {
    .[, .(med_lon = median(lon, na.rm = T), med_lat = median(lat, na.rm = T))]
  }
)
```

```{r}
proj_dist <- function(stations, centers) {
  list(
    aeqd = azeq_fwd(stations, centers[[1]], centers[[2]]) |>
      dist() |>
      as.matrix(),
    utm_auto = utmups_fwd(stations)[, 1:2] |>
      dist() |>
      as.matrix(),
    utm17 = tm_exact_fwd(stations, -81) |>
      dist() |>
      as.matrix(),
    utm18 = tm_exact_fwd(stations, -75) |>
      dist() |>
      as.matrix(),
    utm19 = tm_exact_fwd(stations, -69) |>
      dist() |>
      as.matrix(),
    tm = tm_exact_fwd(stations, centers[[1]]) |>
      dist() |>
      as.matrix(),
    cass = cassini_fwd(stations, centers[[1]], centers[[2]])[, 1:2] |>
      dist() |>
      as.matrix()
  )
}

projected_distances <- mapply(proj_dist, locations, centers, SIMPLIFY = F)
```


```{r}
proj_errs <- function(dists, truth, species) {
  lapply(dists[[species]], \(.) {
    (. - truth[[species]])[lower.tri(truth[[species]])]
  })
}


errors <- sapply(
  names(projected_distances),
  \(.) proj_errs(projected_distances, truth, species = .),
  simplify = FALSE,
  USE.NAMES = TRUE
) |>
  lapply(\(.) as.data.table(.) |> melt()) |>
  rbindlist(idcol = 'species')
```



```{r}
ggplot() +
  geom_histogram(
    data = errors[variable != "utm_auto"],
    aes(x = abs(value), fill = variable),
    position = 'dodge',
    binwidth = 50
  ) +
  geom_vline(xintercept = 500) +
  facet_wrap(~species, scales = "free", ncol = 1)
```

Number greater than 500m distance (receiver detection range)
```{r}
errors[value > 500, .N, c('variable', 'species')]
errors[, sqrt(mean(value^2, na.rm = T)), c('variable', 'species')]
errors[,
  .(min = min(value, na.rm = T), max = max(value, na.rm = T)),
  c('variable', 'species')
]
```


